# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/'
    weight: 10
  - name: Research
    url: '/research/'
    weight: 20
  - name: CBI Data
    url: '/cbi_data/'
    weight: 30
  - name: Other Publications
    url: '/other-pubs/'
    weight: 40
  - name: Teaching
    url: '/teaching/'
    weight: 50
  - name: CV
    url: files/Romelli_CV.pdf
    weight: 60
  - name: Contact
    url: '/contact/'
    weight: 70
